export const STOCK_DAY_PERFORMANCE = "STOCK_DAY_PERFORMANCE";
export const STOCK_OVERVIEW = "STOCK_OVERVIEW";

export const SIGN_OUT = "SIGN_OUT";

export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const CREATE_WATCHLIST = "CREATE_WATCHLIST";
export const FETCH_WATCHLISTS = "FETCH_WATCHLISTS";
export const DELETE_WATCHLIST = "DELETE_WATCHLIST";
